FROM node:18-bullseye

EXPOSE 8080

ENV PL_ASSETS_DIR=/assets
ENV PL_PWA_DIR=/pwa

RUN corepack enable

WORKDIR /padloc

# Only copy over the package manifests + workspace/lock files first.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc tsconfig.json ./
COPY packages/pwa/package.json ./packages/pwa/
COPY packages/app/package.json ./packages/app/
COPY packages/core/package.json ./packages/core/
COPY packages/locale/package.json ./packages/locale/

# Install dependencies for the pwa target and its workspace deps
RUN pnpm install --frozen-lockfile --filter @padloc/pwa...

# Now copy over source files and assets
COPY packages/pwa/src ./packages/pwa/src
COPY packages/pwa/tsconfig.json packages/pwa/webpack.config.js ./packages/pwa/
COPY packages/app/src ./packages/app/src
COPY packages/app/types ./packages/app/types
COPY packages/app/tsconfig.json ./packages/app/
COPY packages/core/src ./packages/core/src
COPY packages/core/vendor ./packages/core/vendor
COPY packages/core/tsconfig.json ./packages/core/
COPY packages/locale/src ./packages/locale/src
COPY packages/locale/res ./packages/locale/res
COPY packages/locale/tsconfig.json ./packages/locale/
COPY assets /assets

WORKDIR /padloc/packages/pwa

ENTRYPOINT ["pnpm", "run"]

CMD ["build_and_start"]
